### PR TITLE
Update Shape_Reconstruction.md

### PR DESCRIPTION
**Pull request by himanshuraj001**

### CODE REVIEW

**Review by ucalyptus — CHANGES_REQUESTED** [review]
Add some images.
Explain how is it better than the previous in its subfield.
Why is this approach interesting and how is it very different from earlier works that it got accepted here.

**Comment by himanshuraj001** [comment]
Actually i have added comparison for 3-d recounstruction i can add one more for 2-d images.

**Comment by himanshuraj001** [comment]
will it be enough.

**Comment by ucalyptus** [comment]
@himanshuraj001 yes

**Pull request closed without merging**
