### PR TITLE
updating fork

### PR DESCRIPTION
**Pull request by soumya997**
cdi

### CODE REVIEW

**Comment by ucalyptus** [comment]
@soumya997 regarding your fork updating issue?

**Comment by soumya997** [comment]
first of all, I could not find options for deleting that commits manually.
that's why I tried with this branch which was not showing any conflicts.

now the thing is I have completed the review for structureflow, so can I upload that?
But, there is not md file left to upload my review.

**Comment by soumya997** [comment]
when I was searching for 'hot to revert previous commits' every video and every article was showing that reverting process using Git...but, I don't know how to use that...

**Comment by ucalyptus** [comment]
@soumya997 contact purbayan

**Pull request closed without merging**
